#!/usr/bin/env bash
# Have bad luck on 4 and good luck on 8
i=1
while [ $i -lt 11 ]
do
	if [ "$i" == 4 ]
	then echo "bad luck"
	elif [ "$i" == 8 ]
	then echo "good luck"
	else
	echo "Best School"
	fi
	((i++))
done	
