#!/usr/bin/env bash
# Superstitous numbers on lines 4, 9, and 17
i=1
while [ $i -le 20 ] 
do 
	echo "$i"
	case $i in
	4)
	"bad luck from China"
	;;
	9)
	"bad luck from Japan"
	;;
	17)
	"bad luck from Italy"
	;;
esac 	((i++))
done
