#!/usr/bin/env bash
#A clock
mintues=1
hour=0
while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	mintutes=1
while [ $minutes -lt 60 ]
do
	echo "$minutes"
	((mintues++))
	done
	((hour++))
	((minutes = 1))
done
